version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8080:80
    image: test-app_nginx
    container_name: "test-app_nginx"

  tomcat:
    build:
      context: .
      dockerfile: ./tomcat/Dockerfile
    ports:
      - 8081:8080
    image: test-app_tomcat
    container_name: "test-app_tomcat"
    networks:
      - test-app-network

  mysql:
    build:
      context: .
      dockerfile: ./mysql-test/Dockerfile
    ports: 
      - 3306:3306
    volumes:
      - ./mysql-test/initdb.d:/docker-entrypoint-initdb.d # 初期処理フォルダ
      - ./mysql-test/db:/var/lib/mysql # データ永続化フォルダ
    image: test-app_mysql
    container_name: "test-app_mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - test-app-network

networks:
  test-app-network:
    driver: bridge
